### ISSUE TITLE
Tutorial on setting up the server

### ISSUE THREAD

**Issue by mechakotik** [udovin/solve#159]
I've managed to get server and web interface working, but it gives error `cannot compile problem: cannot get compiler "polygon.cpp.g++17"` when trying to add problem, and I have no idea on how to build compiler images and where to put them. Could you please add tutorial on setting up a complete test system with web interface and compilers?

**Comment by udovin** [comment]
Yes, this step is poorly described. Compiler setup is provided by the repository https://github.com/udovin/solve-tools. You should use `./solve-tools compilers create` to load compilers onto your system. I'll update the documentation soon.

**Comment by mechakotik** [comment]
Thanks. Just running `./solve-tools compilers create` gave this error: `Error: Account missing permissions. (missing permissions: observe_settings)`. But passing session cookie value from web client fixed the problem.
